
# FROM node:18-alpine
# WORKDIR /app
# RUN apk add --no-cache ffmpeg
# ENV FFMPEG_PATH=ffmpeg
# COPY package*.json ./
# RUN npm ci --omit=dev
# COPY . .
# EXPOSE 3000
# CMD ["node", "server.js"]


FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache ffmpeg
ENV FFMPEG_PATH=ffmpeg

# Install dependencies
COPY package*.json ./
RUN npm install -g nodemon && npm install

# Copy source code
COPY . .

EXPOSE 3000
CMD ["nodemon", "server.js"]
