
# FROM node:18

# WORKDIR /app

# COPY package*.json ./
# RUN npm install

# COPY . .

# EXPOSE 3000
# CMD ["node", "server.js"]

# Alpine with FFmpeg
FROM node:18-alpine
WORKDIR /app

# Install ffmpeg
RUN apk add --no-cache ffmpeg
# RUN apt-get update && apt-get install -y ffmpeg && apt-get clean

# Set ffmpeg path for the application
ENV FFMPEG_PATH=ffmpeg

COPY package*.json ./
RUN npm ci --omit=dev
COPY . .
EXPOSE 3000
CMD ["node", "server.js"]

# FROM node:18-slim 
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci --only=production
# COPY . .
# EXPOSE 3000
# CMD ["node", "server.js"]

